version: '3.8'

services:

  backend:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    container_name: encuesta-api
    image: encuesta-api
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - nestjs-network

  mongodb:
    container_name: encuesta-mongodb
    image: mongo:latest
    networks:
      - nestjs-network
    ports:
      - 27017:27017
    volumes:
      - './mongodb-backup:/data/db'

networks:
  nestjs-network:
    driver: bridge
